steps:
  # Step 1: Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ['install']
    dir: "frontend"

  # Step 2: Build frontend
  - name: "gcr.io/cloud-builders/npm"
    args: ['run', 'build']
    dir: "frontend"

  # Step 3: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args: ['app', 'deploy', 'app.yaml', '--quiet']
    dir: "frontend"

timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY